"""B3: precompute 2–3 deterministic demo scenes.

The output stays in cache/ and is gitignored.
Commit this script, not the generated scene data.
"""

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.attribution.funnel import to_frame
from app.attribution.rank import rank_suspects
from app.attribution.synth import make_scenario
from app.drift.corridor import build_corridor


def cache_scene(scene_id, contract1, seed):
    directory = ROOT / "cache" / scene_id
    directory.mkdir(parents=True, exist_ok=True)

    contract2 = build_corridor(
        contract1,
        field_source="analytic",
        n_members=4,
        n_particles=80,
        max_hours=72,
        rng_seed=seed,
    )

    ais = to_frame(
        make_scenario(
            contract2,
            contract1["orientation_deg"],
            rng_seed=seed,
        )
    )

    suspects = rank_suspects(
        ais,
        contract2,
        contract1["orientation_deg"],
    )

    (directory / "polygon.json").write_text(
        json.dumps(contract1, indent=2)
    )
    (directory / "corridor.json").write_text(
        json.dumps(contract2, indent=2)
    )
    (directory / "suspects.json").write_text(
        json.dumps(suspects, indent=2, default=str)
    )
    ais.to_json(
        directory / "ais.json",
        orient="records",
        date_format="iso",
    )

    print(
        f"cached {scene_id}: "
        f"{len(suspects)} suspects, "
        f"top={suspects[0]['mmsi'] if suspects else None}"
    )


def main():
    contract1 = json.loads(
        (ROOT / "mocks" / "contract1.json").read_text()
    )

    # Three deterministic demo scenes can be generated by changing the seed.
    for scene_id, seed in (
        ("scene_01", 7),
        ("scene_02", 21),
        ("scene_03", 42),
    ):
        cache_scene(scene_id, contract1, seed)


if __name__ == "__main__":
    main()
